[package]
name = "plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
url = "2.3.1"
windows-service = "0.5.0"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-4", "napi-6", "channel-api", "promise-api", "task-api"]

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Foundation",
    "Win32_Networking_HttpServer",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_IO",
    "Win32_System_Memory",
    "Win32_System_Threading",
]

[build-dependencies]
winres = "0.1.12"
